version: '3.1'

services:
  postgresql:
    image: postgres:15.5
    container_name: "postgresql"
    restart: always
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./db/postgresql/data:/var/lib/postgresql/data
    networks:
      net:
        aliases:
          - postgresql
  mariadb:
    image: mariadb:11.4.1-rc
    container_name: "mariadb"
    restart: always
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=mariadb123
    volumes:
      - ./db/mariadb:/var/lib/mysql
    networks:
      net:
        aliases:
          - mariadb
  gen_app:
    image: g14n/nginx-php:8.3.1
    container_name: "gen_app"
    restart: always
    environment:
      - ENVIRONMENT=development
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_KEY=base64:7pWqb+DLKmhMIkjzNp5p9eWQI5QkuX4YK/lF1JBDRfs=
      - APP_DEBUG=true
      - APP_URL=http://localhost:8200
      - DB_CONNECTION=pgsql
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_DATABASE=genesys
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - LOG_CHANNEL=stack
      - LOG_DEPRECATIONS_CHANNEL=null
      - LOG_LEVEL=debug
      - BROADCAST_DRIVER=log
      - CACHE_DRIVER=file
      - FILESYSTEM_DISK=local
      - QUEUE_CONNECTION=sync
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
    ports:
      - "8100:80"
      - "8200:81"
      - "8300:82"
    volumes:
      - ./www:/app/public
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini
      - ./conf/nginx/default.conf:/etc/nginx/http.d/default.conf
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
    tty: true
    networks:
      net:
        aliases:
          - php83

networks:
  net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.0.200.0/24
          gateway: 172.0.200.254
